development:
  adapter: postgresql
  encoding: unicode
  database: simple-user-account-development
  pool: 2


production:
  adapter: postgresql
  encoding: unicode
  database: simple-user-account
  pool: 2
